name = "SpeciesInteractionSamplers"
uuid = "52128aff-513d-4647-bfdb-f540a36539f5"
version = "0.0.1"
authors = ["michael d. catchen <mdcatchen@gmail.com>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
NeutralLandscapes = "71847384-8354-4223-ac08-659a5128069f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpeciesInteractionNetworks = "49e116ef-912f-4766-9e56-896a49944adc"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
Combinatorics = "1.1.0"
DimensionalData = "0.29.25"
Distributions = "0.25"
NeutralLandscapes = "0.1"
SpeciesInteractionNetworks = "0.0.1"
StatsBase = "0.34.10"
TestItems = "1.0"
julia = "1.11"
